### ISSUE TITLE
make failed

### ISSUE THREAD

**Issue by Pslydhh** [cuckoo-trie/cuckoo-trie-code#1]
![image](https://user-images.githubusercontent.com/26759882/139191578-84bb75c2-0cec-4610-8b54-eeb2073685e5.png)
Maybe I shoud change -march?

**Comment by cuckoo-trie** [comment]
Your processor and/or compiler might be too old. Can provide the following, so we can tell if this is the case?
1. Compiler configration (output of `cc -v`)
2. CPU model (output of `grep "model name" /proc/cpuinfo`)
3. Output of `cc -march=native -Q --help=target | grep -- '-march='`

We do not support processor architectures before Haswell because we use instructions that were only introduced in that architecture (e.g. `BEXTR`)

**Comment by Pslydhh** [comment]
1. cc -v:
Using built-in specs.
COLLECT_GCC=/usr/bin/cc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)

2.
model name	: Intel(R) Xeon(R) Platinum 8269CY CPU @ 2.50GHz

3.
  -march=                     		core-avx2

**Comment by cuckoo-trie** [comment]
This version of GCC is too old, and doesn't know about the `-march=haswell` flag and the new instructions that it enables. However, your CPU does support the required instructions.

Compile with a newer version of GCC and it should work (we tested it with GCC 5.4.0 and 7.5.0).
